In [3]:
import numpy as np
r1 = int(input("Enter number of rows for Matrix A: "))
c1 = int(input("Enter number of columns for Matrix A: "))
print("Enter elements of Matrix A:")
A = []
for i in range(r1):
    row = list(map(int, input().split()))
    A.append(row)
r2 = int(input("Enter number of rows for Matrix B: "))
c2 = int(input("Enter number of columns for Matrix B: "))
print("Enter elements of Matrix B:")
B = []
for i in range(r2):
    row = list(map(int, input().split()))
    B.append(row)
A = np.array(A)
B = np.array(B)
if c1 == r2:
    result = np.dot(A, B)      
    print("\nMatrix A:")
    print(A)
    print("\nMatrix B:")
    print(B)
    print("\nDot Product (A × B):")
    print(result)
else:
    print("Matrix multiplication is not possible.")

Enter number of rows for Matrix A:  2
Enter number of columns for Matrix A:  3


Enter elements of Matrix A:


 1 2 3
 4 5 6
Enter number of rows for Matrix B:  3
Enter number of columns for Matrix B:  2


Enter elements of Matrix B:


 1 2
 3 4
 5 6



Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[1 2]
 [3 4]
 [5 6]]

Dot Product (A × B):
[[22 28]
 [49 64]]
