In [1]:
import numpy as np

In [4]:
rows=int(input("No of rows:"))
cols=int(input("No of columns:"))
A=np.zeros((rows,cols),dtype=int)
for i in range(rows):
    for j in range(cols):
        A[i][j]=int(input("Enter element:"))
print(A)
print("Rank of matrix: ",np.linalg.matrix_rank(A))

No of rows: 3
No of columns: 3
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 0
Enter element: 0
Enter element: 0
Enter element: 4
Enter element: 5
Enter element: 6


[[1 2 3]
 [0 0 0]
 [4 5 6]]
Rank of matrix:  2
