In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
rows=int(input("No of rows:"))
cols=int(input("No of columns:"))
A=np.zeros((rows,cols),dtype=int)
for i in range(rows):
    for j in range(cols):
        A[i][j]=int(input("Enter element:"))
transpose=np.zeros((cols,rows),dtype=A.dtype)
for i in range(rows):
    for j in range(cols):
        transpose[j][i]=A[i][j]
print("Original Matrix")
print(A)
print("\nTranspose of A")
print(transpose)

No of rows: 2
No of columns: 3
Enter element: 1
Enter element: 2
Enter element: 3
Enter element: 4
Enter element: 5
Enter element: 6


Original Matrix
[[1 2 3]
 [4 5 6]]

Transpose of A
[[1 4]
 [2 5]
 [3 6]]
